steps:
  # Deploy to europe-west1 using the image from europe-central2
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get the latest image from europe-central2
        IMAGE_URL="europe-central2-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${REPO_NAME}/dlv-saas-d:${COMMIT_SHA}"
        
        # Deploy to europe-west1
        gcloud run deploy dlvinsight-app \
          --image=$$IMAGE_URL \
          --region=europe-west1 \
          --platform=managed \
          --no-allow-unauthenticated \
          --set-env-vars="NODE_ENV=production,NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${_CLERK_PUBLISHABLE_KEY},CLERK_SECRET_KEY=${_CLERK_SECRET_KEY},NEXT_PUBLIC_CLERK_SIGN_IN_URL=${_CLERK_SIGN_IN_URL},NEXT_PUBLIC_CLERK_SIGN_UP_URL=${_CLERK_SIGN_UP_URL},DATABASE_URL=${_DATABASE_URL},BILLING_PLAN_ENV=${_BILLING_PLAN_ENV},NEXT_PUBLIC_APP_NAME=DLV Insight,NEXT_PUBLIC_APP_DESCRIPTION=Amazon Seller Profit Analytics Platform,NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${_STRIPE_PUBLISHABLE_KEY},STRIPE_SECRET_KEY=${_STRIPE_SECRET_KEY}" \
          --add-cloudsql-instances=dlvinsight-profit-analytics:europe-central2:dlvinsight-db